---
# title: "Plot location"
# author: "Miquel De Cáceres/Adriana Tovar"
# date: "2025-02-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(out.width="85%")
library(dplyr)
library(knitr)
library(kableExtra)
library(ggplot2)
```

## Plot location

```{r, echo=FALSE, include=FALSE}

i <- which(plots_cat$id_unique_code==id)


treeData4 <- plots_cat$tree[[i]]
treeData3 <- NULL
sel3 <- which(ifn3_cat$id_unique_code==id)
# Extraer las coordenadas de la parcela
coords<-plots_ph_wgs |> 
  dplyr::filter(id_unique_code  == id
  ) |> 
  dplyr::select(lon_wgs84 ,lat_wgs84,coordx_ed50,coordy_ed50  ) 


municipio<-plots_ph_wgs |> 
  data.frame() |> 
  dplyr::filter(id_unique_code  == id
  ) |> 
  dplyr::select(NOMMUNI) |> pull()

if(length(sel3) == 1) treeData3 <- ifn3_cat$tree[[sel3]]

```

| Persona | Localidad | Hora | Fecha |
|---------|-----------|------|-------|
|         |           |      |       |

<br>

###### `r paste0("Municipio: ",municipio)`

###### `r paste0("Número de la parcela: ",id)`

###### `r paste0("Coordenadas de la parcela en  LON ,LAT: (", coords$lon_wgs84 , ", ", coords$lat_wgs84 , ")")`

###### `r paste0("Coordenadas de la parcela en  UTM ED50: (", coords$coordx_ed50  , ", ", coords$coordy_ed50  , ")")`

###### Coordenadas GPS:

###### Comentarios:

<br>

```{r, echo=FALSE, fig = TRUE, fig.width=13, fig.height=10, fig.align="center", warning=FALSE}
plot_tree_data(treeData4, treeData3,scale_factor = 1)
```

```{r, echo=FALSE,  warning=FALSE}

plots_ph_topo<-plots_ph_wgs_All |> 
  dplyr::filter(
    id_unique_code == id
  ) |> 
  dplyr::select(
    id = id_unique_code,
    Localiza,
    Acceso,
    Levanta,
    FccArb,
    altitud,
    Orienta1,
    MaxPend1,
    Rocosid
  )
```

```{r, echo=FALSE,  warning=FALSE}
knitr::kable(plots_ph_topo, caption = "Topo table", format = "html") |> 
  kableExtra::kable_styling(
    bootstrap_options = c("striped", "hover"),
    full_width = TRUE,  # La tabla ocupará todo el espacio disponible
    position = "center",
    font_size = 8  # Tamaño de fuente más pequeño
  ) |> 
  kableExtra::column_spec(1:ncol(plots_ph_topo), border_left = TRUE, border_right = TRUE)

```

###### stratification

###### 1 (0 \< H ≤ 1/4 Ho) [ ] 2 (1/4 \< H ≤ 1/2 Ho) [ ]3 (1/2 \< H ≤ 3/4 Ho) [ ] 4 (3/4 \< H ≤ Ho) [ ]5 ( Hem \> Ho) [ ]
