---
# title: "Regen table"
# author: "Miquel de Cáceres/ Adriana Tovar"
date: "2025-02-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(knitr)
library(kableExtra)
```

### Regen sampling

```{r, echo=FALSE, include=FALSE}

i <- which(plots_cat$id_unique_code==id)


```

|  Name   |  Place    | Time | Date  |
|---------|-----------|------|-------|
|         |           |      |       |

<br>
<br>
<br>


#### `r paste0("PLOT NUMBER: ")`

#### Regeneration sampling within the 5m radius plot 

```{r, echo=FALSE, warning=FALSE}



#opcion 2
regen_Datatable <- data.frame() |>
  dplyr::mutate(
    sp_name = character(),
    Catdes1 = character(),
    Catdes2 = character(),
    Catdes3 = character(),
    Catdes4 = character(),
    height_cat4 = character()
  ) |>
  dplyr::arrange(sp_name) 

# Agregar 40 filas vacías
regen_Datatable <- regen_Datatable |>
  dplyr::bind_rows(data.frame(
    sp_name = rep(" ", 30),
    Catdes1 = rep(" ", 30),
    Catdes2 = rep(" ", 30),
    Catdes3 = rep(" ", 30),
    Catdes4 = rep(" ", 30),
    height_cat4 = rep(" ", 30)
  ))


```



```{r, echo=FALSE, warning=FALSE}
# Mostrar ambas tablas

knitr::kable(regen_Datatable,  format = "html") |> 
  kableExtra::kable_styling(
    bootstrap_options = c("striped", "hover"),
    full_width = TRUE,
    position = "center",
    font_size = 8
  ) |> 
  kableExtra::column_spec(1:ncol(regen_Datatable), border_left = TRUE, border_right = TRUE)
```
<br>
Comments:
<br>
